name: kilo_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0
  shared_preferences: ^2.0.0

  cupertino_icons: ^1.0.3
  splash_screen_view: ^3.0.0
  intro_views_flutter: ^3.2.0
  flutter_tabler_icons: ^1.1.1
  awesome_dialog: ^2.1.0
  awesome_loader: ^0.0.3
  awesome_button: ^1.0.2
  toggle_switch: ^1.1.0
  flutter_staggered_animations: ^1.0.0
  fancy_bottom_navigation: ^0.3.3
  easy_localization: ^3.0.0
  camera: ^0.5.8+5
  tflite: ^1.1.1
  path_provider: ^2.0.2
  image_picker: ^0.6.4
  compressimage: ^0.1.1
  flutter_exif_rotation: ^0.2.7
  image: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/machine/

  fonts:
    - family: Original Surfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

